logging:
  level:
    it.adt: DEBUG
    #it.adt.comparison: DEBUG
    #it.adt.comparison.service: WARN
server:
  port: 8080
my-properties:
  name: Pino

# DATASOURCE
spring:
  datasource:
    url: "jdbc:postgresql://shoptest-postgresql:5432/postgres?currentSchema=shop_test"
    #url: "jdbc:postgresql://localhost:5432/postgres?currentSchema=shop_test"
    username: postgres
    password: root
    driver-class-name: "org.postgresql.Driver"
  # JPA - Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    database-platform: "org.hibernate.dialect.PostgreSQL95Dialect"
    properties:
      hibernate.default_schema: shop_test