logging:
  level:
    it.adt: DEBUG
    #it.adt.comparison: DEBUG
    #it.adt.comparison.service: WARN
server:
  port: 8080
my-properties:
  name: Pino
  cron:
    expression: 0/5 * * * * ?

# DATASOURCE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  enable:
    scheduling: true

  # JPA - Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.default_schema: shop_test
  # KAFKA
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      group-id: "EdgeApplication"
    security:
      enabled: false
    custom:
      properties:
        sasl:
          mechanism: "PLAIN"
          jaas:
            class: "org.apache.kafka.common.security.plain.PlainLoginModule"
            user: "admin"
            password: "12345"
        trust:
          store:
            location: "location of truststore"
            password: "trust store password"
        ssl:
          endpoint:
            identification:
              algorithm: ""
        security:
          protocol: "SASL_PLAINTEXT"

education-maria:
  kafka:
    topic:
      publish-message:
        output: purchase.v1
      listen-message:
        input: purchase.v1